### PR TITLE
update auto-install in Readme

### PR DESCRIPTION
**Pull request by harsham05**
./start.sh script uses $OODT_HOME as ~/deploy

### CODE REVIEW

**Comment by chrismattmann** [comment]
Thanks @harsham05 !

**Comment by chrismattmann** [comment]
BTW were you able to ingest some images?

**Comment by harsham05** [comment]
You're welcome Professor. But when trying to run ImageCat chunker (Step 14), I get the following error,

> > $OODT_HOME/bin/chunker 
> > ERROR: Option [longOption='url',shortOption='u',description='Workflow Manager URL'] requires args

**Comment by chrismattmann** [comment]
you didn't source your envs or you don't have WORKFLOW_URL defined. Please confirm. @harsham05

**Pull request merged**
